spring.application.name=ATM-Project
server.port=5000

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/atmdb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=tiger

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=5367566859703373367639792F423F452848284D6251655468576D5A71347437
jwt.expiration=900000

# Logging
logging.level.root=INFO
logging.level.com.prabhas=DEBUG